export const GET_BEERS_START = 'GET_BEERS_START';
export const GET_BEERS_SUCCESS = 'GET_BEERS_SUCCESS';
export const GET_BEERS_FAIL = 'GET_BEERS_FAILED';
export const CLEAN_BEERS = 'CLEAN_BEERS';

export const UPDATE_FAVORITES_SUCCESS = 'UPDATE_FAVORITES_SUCCESS';
